### ISSUE TITLE
LTTA possibly causing Guidebook crash?

### ISSUE THREAD

**Issue by Geethebluesky** [TheFloydman/LTTA#1]
https://github.com/gigaherz/Guidebook/issues/48

Opened an issue based on the crashlog I got: gigaherz indicates the error may be on LTTA's side though. Let me know if you need more info, relevant logs repasted here:

[Crash log](https://gist.github.com/Geethebluesky/ce672614de26dd4a6a93d792e348dac4)

More helpful [segment from debug.log](https://gist.github.com/Geethebluesky/fa15c82d79721c911ab1509e671520d4) showing the crash happens right after LTTA is referenced

**Comment by TheFloydman** [comment]
There was an issue with LTTA referencing a class from Guidebook that hadn't been loaded yet. LTTA will now load *after* Guidebook to ensure that doesn't happen.

**Comment by TheFloydman** [comment]
New file (1.1.0) is currently pending on CurseForge.
