### ISSUE TITLE
Ink recipe shown needs uncraftable potion.

### ISSUE THREAD

**Issue by Geethebluesky** [TheFloydman/LTTA#2]
This is the first page of the LTTA book for me:

![image](https://user-images.githubusercontent.com/1903792/41511464-3c8ef31a-7234-11e8-9181-fc60c698d948.png)

For some reason, the book opts to show the recipe above with the potion, instead of the more accessible one shown here in JEI:

![image](https://user-images.githubusercontent.com/1903792/41511468-58de07ea-7234-11e8-97db-ae9fe6d6e7a4.png)

Not sure what info to give you to help resolve this?

**Comment by TheFloydman** [comment]
Thank you. I'm currently unsure how to fix this. As far as I can tell, the Water Bottle item is actually a Potion item with an NBT of 0, but that displays the uncraftable potion that you see. I will give it a closer look this week.

**Comment by TheFloydman** [comment]
Oh, I see, I could add the glass bottle+water bucket recipe. I like that idea.

**Comment by Geethebluesky** [comment]
If the recipe shown is dependent on Minecraft and that NBT value, I suppose an alternative would just be to say "You can also craft this using a full water bottle and 2 black inks" or something similar?

**Comment by TheFloydman** [comment]
Alright, I figured out how to correctly display the Water Bottle, so I fixed that along with a few other NBT updates. I also added the second recipe, so they are both displayed. Also some small improvements (like links in the quick guides to make finding modifiers easier). 1.2.1 is live now: https://minecraft.curseforge.com/projects/ltta/files/2573837

**Comment by Geethebluesky** [comment]
Thank you! :)
