### ISSUE TITLE
Color blending error, page 24

### ISSUE THREAD

**Issue by keybounce** [TheFloydman/LTTA#3]
the example given on page 24 of the guidebook, red color blue color, will result in a color that is exactly half red, and half blue. (128, zero, 128). Colors are always pairwise averaged.

I believe (but have not tested, this is memory) that the order is left to right -- when a color is seen, the existing color value is averaged with the new color symbol, and then that result is saved to either be averaged again in the future or used.

**Comment by keybounce** [comment]
If my order is correct, then the last color has the greatest weight, not the first.

**Comment by TheFloydman** [comment]
Thank you. I saw your conversation on Discord, and Veovis confirmed this as well. I'll correct it ASAP.

**Comment by TheFloydman** [comment]
How does this sound?

> Things become more complicated when you add several modifier Pages before a feature Page. For modifiers that can be combined, the first modifier is averaged with the one after it, and that combined modifier is averaged with the next modifier, and so on. For example,
> 
> _Red + Blue + Green + Sky Color_
> 
> will produce a sky color that is an average of purple and green. You will mostly use combined modifiers when dealing with colors and directions.

**Comment by keybounce** [comment]
That sounds good.

**Comment by keybounce** [comment]
Actually, you'll need to add in a comment about the clockwise averaging of
directions, (Vio's example of West + North), and the similar thing about
the sky directions.

**Comment by keybounce** [comment]
> Vio's example of West + North),
>

Veo. Not Vio.

>

**Comment by TheFloydman** [comment]
Thanks for your help on this. I just submitted a file (1.2.3) with updated information about averaging modifiers. I will probably flesh it out more when I expand the Grammar section.
