### ISSUE TITLE
LTTA v 1.3.1 for MC 1.12.2 - Library chest missing

### ISSUE THREAD

**Issue by Ashendale** [TheFloydman/LTTA#7]
I imagine this has something to do with this mod, as it never happened before, and there was this recent fix about the library chest being full of Narayani for Dummies.

Forge version: 14.23.4.2765

If I can provide any more relevant details, please let me know.

**Comment by TheFloydman** [comment]
Hmm, I don't see how it could delete the chest since all I did was change an integer from 50 to 25, but I'll take a look.

**Comment by TheFloydman** [comment]
I am unable to recreate this issue with Forge 14.23.4.2765, Mystcraft 0.13.6.00, Guidebook 2.8.3, and LTTA 1.3.1. Can you share your game logs?

**Comment by Ashendale** [comment]
Which logs can I provide (what can I do, and where can I fetch them from?)?

**Comment by TheFloydman** [comment]
They are inside the "logs" folder inside of your Minecraft instance. Run a new world until you get the issue, then quit. I will need the 2 newest files in the folder. If you need more help finding the folder, I would direct you to Google, as others can explain it better than I. Also, are your playing a specific modpack?

**Comment by Ashendale** [comment]
I am also having a hard time reproducing. I am playing a personal pack. If I come across the issue, I'll provide the logs as well as the mod list. I guess you can close this issue. Thank you for the fast responses.
